---
title: "Building an Enterprise GIS Workflow with QGIS and PostGIS"
author: "Gispo Ltd."
date: "`r Sys.Date()`"
site: "bookdown::bookdown_site"
abstract: "Workshop delivered in FOSS4G Prizren 2023."
output:
    bookdown::html_book:
        toc: true
        theme: null
        template: custom.html
        css: custom.css
        split_by: rmd
documentclass: book
---

<!-- Exercises -->

# Template

## Welcome!

Workshop Objectives:

\- Create an enterprise GIS workflow using QGIS and PostGIS.

\- Explore the benefits of spatial databases and their role in GIS data management.

\- Set up QGIS projects to optimize GIS data management.

# Reading instructions

**Web-selaimessa** suoritettavat komennot on merkitty seuraavasti:

::: note-box
<http://localhost:8080/geoserver>
:::

**Komentorivillä** suoritettavat komennot on merkitty seuraavasti:

::: commandline-box
sudo lsb_release -a
:::

**Tiedostojen sisältö** on esitetty seuraavasti:

::: file-content-box
#IPv4 local connections: #host all all 127.0.0.1/32 md5
:::

**HTML- ja CSS-koodit, SQL-komennot sekä Python-scriptit** on esitetty seuraavasti:

::: code-box
SELECT version();
:::

**Kysymykset, lisätiedot ja vihjeet** on esitetty seuraavasti:

::: hint-box
Mistä löydät tietoa GeoServeristä?

GeoServerillä on omat kotisivut.

Psst! Tietoa GeoServeristä löydät internetistä.
:::

## Mistä lisätietoja?

Ohessa muutamia web-sivustoja, joista saat lisätietoja:

::: note-box
<http://www.qgis.org/>
:::

::: note-box
<http://docs.qgis.org/>
:::

::: note-box
<http://gis.stackexchange.com/>
:::

::: note-box
<http://www.osgeo.fi>
:::

## Errors

Jos havaitset materiaalissa virheitä, niin pyydämme ilmoittamaan niistä kouluttajalle tai sähköpostilla [info\@gispo.fi-osoitteeseen](mailto:info@gispo.fi-osoitteeseen){.email}.

## License and user rights

These materials are developed by Gispo Ltd. Materials are licensed under: [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/)
